Sescandell\SimpleNewsletterBundle\Model\Newsletter:
    type: mappedSuperclass
    fields:
        subject:
            type: string
            length: 255
        content:
            type: text
        placeholders:
            type: boolean
        sentAt:
            column: sent_at
            type: datetime
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
